# Generated by Django 2.0.4 on 2018-04-23 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20180423_1221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Jugadores'},
        ),
    ]
