# Generated by Django 2.0.4 on 2018-04-23 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20180423_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Jugador'},
        ),
    ]
